# Generated by Django 3.2.8 on 2021-10-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('supplier_website', models.URLField()),
                ('supplier', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('origin_country', models.CharField(max_length=100)),
                ('origin_region', models.CharField(max_length=140)),
                ('origin_variety', models.CharField(max_length=140)),
                ('process', models.CharField(max_length=100)),
                ('harvest', models.CharField(max_length=140)),
                ('drying', models.CharField(max_length=100)),
                ('altitude_min', models.SmallIntegerField()),
                ('altitude_max', models.SmallIntegerField()),
                ('decaffeinated', models.BooleanField()),
                ('certified_organic', models.BooleanField()),
                ('certified_fairtrade', models.BooleanField()),
                ('certified_rainforestalliance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(max_length=13, unique=True)),
                ('roasted_on', models.DateTimeField()),
                ('roast_profile', models.CharField(max_length=140)),
                ('roast_log', models.FileField(upload_to='uploads/')),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.bean')),
            ],
        ),
    ]
