# Generated by Django 3.2.8 on 2021-10-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Starting weight in grams', max_digits=5),
            preserve_default=False,
        ),
    ]
