# Generated by Django 3.2.8 on 2021-10-13 18:35

import coffee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_bean_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bean',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='roast',
            name='public_id',
        ),
        migrations.AddField(
            model_name='bean',
            name='slug',
            field=models.SlugField(default=coffee.models.assign_id, editable=False),
        ),
        migrations.AddField(
            model_name='roast',
            name='slug',
            field=models.SlugField(default=coffee.models.assign_id, editable=False),
        ),
    ]
