# Generated by Django 3.2.8 on 2021-10-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_auto_20211013_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bean',
            name='altitude_max',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bean',
            name='altitude_min',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
