# Generated by Django 3.2.8 on 2021-10-17 15:24

import coffee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_auto_20211013_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default=coffee.models.assign_id, editable=False)),
                ('display_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bean',
            options={'ordering': ['-delivered_on']},
        ),
        migrations.AlterModelOptions(
            name='roast',
            options={'ordering': ['-roasted_on']},
        ),
    ]
