# Generated by Django 3.2.8 on 2021-10-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_auto_20211017_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='roaster',
            field=models.CharField(default='Behmor 2000AB Plus', max_length=255),
        ),
        migrations.AddField(
            model_name='roast',
            name='time_to_cooling',
            field=models.PositiveIntegerField(default=820, help_text='Time to cooling in seconds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roast',
            name='time_to_first_crack',
            field=models.PositiveIntegerField(default=700, help_text='Time to first crack in seconds'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roast',
            name='roast_quantity',
            field=models.DecimalField(decimal_places=1, help_text='Yield weight in grams', max_digits=5),
        ),
    ]
