# Generated by Django 3.2.8 on 2021-10-17 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_auto_20211017_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='roast_level',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='roast',
            name='roast_log',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
