# Generated by Django 3.2.8 on 2021-10-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_auto_20211017_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roast',
            name='degree_of_roast',
        ),
    ]
